parameters:
    # twig
    shapecode.twig_string_loader.twig_loader.chain.class: %twig.loader.chain.class%
    shapecode.twig_string_loader.twig_loader.string.class: Shapecode\Bundle\TwigStringLoaderBundle\Twig\Loader\StringLoader

services:

    # twig
    shapecode.twig_string_loader.twig_loader.string:
        class: %shapecode.twig_string_loader.twig_loader.string.class%
        tags:
            - { name: twig.loader }

    shapecode.twig_string_loader.twig_loader.chain:
        class: %shapecode.twig_string_loader.twig_loader.chain.class%
        calls:
            - [ "addLoader", ["@twig.loader"] ]
            - [ "addLoader", ["@shapecode.twig_string_loader.twig_loader.string"] ]
