parameters:

    # twig
    shapecode.twig_string_loader.twig_loader.string.class: Shapecode\Bundle\TwigStringLoaderBundle\Twig\Loader\StringLoader

services:

    # twig
    shapecode.twig_string_loader.twig_loader.string:
        class: %shapecode.twig_string_loader.twig_loader.string.class%
        tags:
            - { name: twig.loader }
